### PR TITLE
fix(stringify): should not throw error

### LINKED ISSUE #55: stringify: return `undefined` if impossible to stringify BEM notation
now need use `try..catch`:

```js
try {
    var str = bemNaming.stringify({ elem: 'elem' });
} catch(e) { /* ... */ }
```

it will be easier to check for an empty string:

```js
var str = bemNaming.stringify({ elem: 'elem' });

if (str) {
    /* ... */ 
}
```

### PR DESCRIPTION
**Pull request by blond**
Resolved #55 

The stringify method should return `undefined` if impossible to
stringify BEM notation.

It will be easier to check for an empty string than use `try..catch`.

**Before changes:**

```js
try {
    var str = bemNaming.stringify({ elem: 'elem' });
} catch(e) { /* ... */ }
```

**After changes:**

```js
var str = bemNaming.stringify({ elem: 'elem' });

if (str) {
    /* ... */
}
```

### CODE REVIEW

File: index.js [hunk 1]
```diff
@@ -68,7 +68,7 @@ BEMNaming.prototype.typeOf = function (obj) {
         obj = this.parse(obj);
     }
 
-    if (!obj || !obj.block) { return; }
+    if (!obj || !obj.block) { return undefined; }
```
Comment (tadatuta) [inline index.js]: isn't it just the same as before but with more letters? )

Comment (blond) [inline index.js]: yep, but it is more obviously

Comment (tadatuta) [inline index.js]: well... I think previous variant was better but still lgtm :)
