### PR TITLE
fix(fields): does not delim fields

### LINKED ISSUE #77: Does not delim fields
Now namespace includes methods, but not includes `elemDelim` and `modDelim` fields.

**Example:**

```js
import naming from 'bem-naming';

console.log(naming.elemDelim);
console.log(naming.modDelim);
```

**Actual:**

```
undefined
undefined
```

**Expected:**

```
__
_
```

Broken in https://github.com/bem/bem-naming/pull/72

### PR DESCRIPTION
**Pull request by blond**
Resolved #77 

The default namespace and namespaces with custom naming should includes
`elemDelim` and `modDelim` fields.

### CODE REVIEW

File: index.js [hunk 1]
```diff
@@ -216,14 +217,17 @@ var defineAsGlobal = true,
...
+        });
         cache[id] = namespace;
 
         return namespace;
     },
     originalNaming = bemNaming();
 
-methods.forEach(function (method) {
-    bemNaming[method] = originalNaming[method];
+[].concat(methods, fields).forEach(function (name) {
```
Comment (tadatuta) [inline index.js]: `methods.concat(fields)`?

Comment (blond) [inline index.js]: fix
